name: Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow only when a tag matching 'v*' is pushed

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev libx11-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Dependencies
      run: go mod tidy
  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Build macOS Binaries
      run: |
        mkdir -p bin
        CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-darwin-amd64 .
        CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-darwin-arm64 .

    - name: Compress macOS Binaries
      run: |
        mkdir -p release/macos
        zip -j release/macos/BadgerWorkbench-${{ github.ref_name }}-darwin-amd64.zip bin/BadgerWorkbench-${{ github.ref_name }}-darwin-amd64
        zip -j release/macos/BadgerWorkbench-${{ github.ref_name }}-darwin-arm64.zip bin/BadgerWorkbench-${{ github.ref_name }}-darwin-arm64

    - name: Upload macOS Binaries
      uses: actions/upload-artifact@v4
      with:
        name: macos-bin
        path: release/macos

  build-windows:
    name: Build Windows Binaries
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Build for Windows (amd64 and 386)
      env:
        CC: x86_64-w64-mingw32-gcc
      run: |
        mkdir -p bin
        CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -o bin/BadgerWorkbench-${{ github.ref_name }}-windows-amd64.exe .
        CGO_ENABLED=1 GOOS=windows GOARCH=386 CC=i686-w64-mingw32-gcc go build -o bin/BadgerWorkbench-${{ github.ref_name }}-windows-386.exe .

    - name: Compress Windows Binaries
      run: |
        mkdir -p release/windows
        zip -j release/windows/BadgerWorkbench-${{ github.ref_name }}-windows-amd64.zip bin/BadgerWorkbench-${{ github.ref_name }}-windows-amd64.exe
        zip -j release/windows/BadgerWorkbench-${{ github.ref_name }}-windows-386.zip bin/BadgerWorkbench-${{ github.ref_name }}-windows-386.exe

    - name: Upload Windows Binaries
      uses: actions/upload-artifact@v4
      with:
        name: windows-bin
        path: release/windows

  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1-mesa-dev \
          xorg-dev \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxi-dev \
          libxinerama-dev \
          gcc

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Build for Linux (amd64)
      run: |
        mkdir -p bin
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o bin/BadgerWorkbench-${{ github.ref_name }}-linux-amd64 .

    - name: Compress Linux Binary
      run: |
        mkdir -p release/linux
        zip -j release/linux/BadgerWorkbench-${{ github.ref_name }}-linux-amd64.zip bin/BadgerWorkbench-${{ github.ref_name }}-linux-amd64

    - name: Upload Linux Binaries
      uses: actions/upload-artifact@v4
      with:
        name: linux-bin
        path: release/linux

  package-and-upload:
    name: Package and Upload Release Assets
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows, build-linux]
    permissions:
      contents: write # Explicitly grant write access to contents for uploading assets
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this release
          - Automatically generated release notes.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download macOS Binaries
      uses: actions/download-artifact@v4
      with:
        name: macos-bin
        path: release/macos

    - name: Download Windows Binaries
      uses: actions/download-artifact@v4
      with:
        name: windows-bin
        path: release/windows

    - name: Download Linux Binaries
      uses: actions/download-artifact@v4
      with:
        name: linux-bin
        path: release/linux

    - name: Upload macOS AMD64 Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/macos/BadgerWorkbench-${{ github.ref_name }}-darwin-amd64.zip
        asset_name: BadgerWorkbench-${{ github.ref_name }}-darwin-amd64.zip
        asset_content_type: application/zip

    - name: Upload macOS ARM64 Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/macos/BadgerWorkbench-${{ github.ref_name }}-darwin-arm64.zip
        asset_name: BadgerWorkbench-${{ github.ref_name }}-darwin-arm64.zip
        asset_content_type: application/zip

    - name: Upload Windows AMD64 Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/windows/BadgerWorkbench-${{ github.ref_name }}-windows-amd64.zip
        asset_name: BadgerWorkbench-${{ github.ref_name }}-windows-amd64.zip
        asset_content_type: application/zip

    - name: Upload Windows 386 Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/windows/BadgerWorkbench-${{ github.ref_name }}-windows-386.zip
        asset_name: BadgerWorkbench-${{ github.ref_name }}-windows-386.zip
        asset_content_type: application/zip

    - name: Upload Linux AMD64 Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/linux/BadgerWorkbench-${{ github.ref_name }}-linux-amd64.zip
        asset_name: BadgerWorkbench-${{ github.ref_name }}-linux-amd64.zip
        asset_content_type: application/zip