name: Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow only when a tag matching 'v*' is pushed

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Dependencies
      run: go mod tidy

    - name: Build for macOS (amd64 and arm64)
      run: |
        mkdir -p bin
        CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-darwin-amd64 .
        CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-darwin-arm64 .

    - name: Build for Windows (amd64 and 386)
      run: |
        mkdir -p bin
        CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-windows-amd64.exe .
        CC=i686-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=386 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-windows-386.exe .

    - name: Build for Linux (amd64 and arm64)
      run: |
        mkdir -p bin
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-linux-amd64 .
        CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o bin/BadgerWorkbench-${{ github.ref_name }}-linux-arm64 .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this release
          - Automatically generated release notes.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/
        asset_name: ${{ runner.os }}-binaries
        asset_content_type: application/zip
